version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
        environment:
          JAVA_OPTS: -Xmx3200m
          GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx3200m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: sdks-licenses-build-tools-extras-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          working_directory: AndroidStudio
      - save_cache:
          key: sdks-licenses-build-tools-extras-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - /opt/android/sdk/licenses
            - /opt/android/sdk/build-tools
            - /opt/android/sdk/extras
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: Test
          command: ./gradlew --stacktrace lint testDebug
          working_directory: AndroidStudio
      - run:
          name: Danger
          command: bundle exec danger
          #      - store_artifacts:
          #path: app/build/reports
          #destination: reports
          #- store_artifacts:
          #path: app/build/test-results
          #destination: test-results
          #- store_artifacts:
          #path: app/build/outputs/apk
          #destination: apk
